name: 'jaffle_shop_minimal'
version: '1.0.0'
config-version: 2

profile: 'jaffle_shop_minimal'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  jaffle_shop_minimal:
    staging:
      +materialized: view
    marts:
      +materialized: table
