import json

manifest = {
    'metadata': {
        'dbt_schema_version': 'https://schemas.getdbt.com/dbt/manifest/v5.json',
        'dbt_version': '1.5.0',
        'generated_at': '2024-01-15T10:30:00Z',
        'project_name': 'ecommerce_analytics',
    },
    'nodes': {},
    'sources': {},
    'parent_map': {},
    'child_map': {},
}

# --- SOURCES ---
sources = {
    'source.ecommerce.raw_orders': {
        'name': 'raw_orders',
        'resource_type': 'source',
        'unique_id': 'source.ecommerce.raw_orders',
        'description': 'Raw order transactions from the e-commerce platform',
        'relation_name': '"ecommerce"."raw_orders"',
        'columns': {
            'order_id': {'data_type': 'VARCHAR', 'description': 'Primary key'},
            'customer_id': {'data_type': 'INTEGER', 'description': 'Customer FK'},
            'order_date': {'data_type': 'TIMESTAMP', 'description': 'When order was placed'},
            'status': {'data_type': 'VARCHAR', 'description': 'pending/confirmed/shipped/delivered/cancelled'},
            'total_amount': {'data_type': 'DECIMAL', 'description': 'Total order value'},
            'discount_amount': {'data_type': 'DECIMAL', 'description': 'Discount applied'},
            'shipping_cost': {'data_type': 'DECIMAL', 'description': 'Shipping charge'},
            'payment_method': {'data_type': 'VARCHAR', 'description': 'credit_card/paypal/apple_pay'},
            'shipping_address_id': {'data_type': 'INTEGER', 'description': 'Address FK'},
            'created_at': {'data_type': 'TIMESTAMP', 'description': 'Record creation time'},
        },
        'depends_on': {'nodes': []},
        'raw_sql': '',
        'compiled_sql': '',
    },
    'source.ecommerce.raw_customers': {
        'name': 'raw_customers',
        'resource_type': 'source',
        'unique_id': 'source.ecommerce.raw_customers',
        'description': 'Customer master data',
        'relation_name': '"ecommerce"."raw_customers"',
        'columns': {
            'customer_id': {'data_type': 'INTEGER', 'description': 'Primary key'},
            'email': {'data_type': 'VARCHAR', 'description': 'Email address'},
            'first_name': {'data_type': 'VARCHAR', 'description': 'First name'},
            'last_name': {'data_type': 'VARCHAR', 'description': 'Last name'},
            'phone': {'data_type': 'VARCHAR', 'description': 'Phone number'},
            'created_at': {'data_type': 'TIMESTAMP', 'description': 'Account creation date'},
            'country': {'data_type': 'VARCHAR', 'description': 'Country code'},
            'city': {'data_type': 'VARCHAR', 'description': 'City'},
            'customer_segment': {'data_type': 'VARCHAR', 'description': 'retail/wholesale/vip'},
            'lifetime_value': {'data_type': 'DECIMAL', 'description': 'Customer lifetime value'},
        },
        'depends_on': {'nodes': []},
        'raw_sql': '',
        'compiled_sql': '',
    },
    'source.ecommerce.raw_products': {
        'name': 'raw_products',
        'resource_type': 'source',
        'unique_id': 'source.ecommerce.raw_products',
        'description': 'Product catalog',
        'relation_name': '"ecommerce"."raw_products"',
        'columns': {
            'product_id': {'data_type': 'INTEGER', 'description': 'Primary key'},
            'sku': {'data_type': 'VARCHAR', 'description': 'Stock keeping unit'},
            'product_name': {'data_type': 'VARCHAR', 'description': 'Product display name'},
            'category': {'data_type': 'VARCHAR', 'description': 'Product category'},
            'subcategory': {'data_type': 'VARCHAR', 'description': 'Product subcategory'},
            'brand': {'data_type': 'VARCHAR', 'description': 'Brand name'},
            'unit_price': {'data_type': 'DECIMAL', 'description': 'List price'},
            'cost': {'data_type': 'DECIMAL', 'description': 'Cost of goods'},
            'is_active': {'data_type': 'BOOLEAN', 'description': 'Currently sellable'},
            'weight_kg': {'data_type': 'DECIMAL', 'description': 'Shipping weight'},
        },
        'depends_on': {'nodes': []},
        'raw_sql': '',
        'compiled_sql': '',
    },
    'source.ecommerce.raw_marketing': {
        'name': 'raw_marketing',
        'resource_type': 'source',
        'unique_id': 'source.ecommerce.raw_marketing',
        'description': 'Marketing campaign and attribution data',
        'relation_name': '"ecommerce"."raw_marketing"',
        'columns': {
            'campaign_id': {'data_type': 'INTEGER', 'description': 'Primary key'},
            'campaign_name': {'data_type': 'VARCHAR', 'description': 'Campaign display name'},
            'channel': {'data_type': 'VARCHAR', 'description': 'google/facebook/email/affiliate'},
            'start_date': {'data_type': 'DATE', 'description': 'Campaign start'},
            'end_date': {'data_type': 'DATE', 'description': 'Campaign end'},
            'budget': {'data_type': 'DECIMAL', 'description': 'Campaign budget'},
            'spend': {'data_type': 'DECIMAL', 'description': 'Actual spend'},
            'impressions': {'data_type': 'INTEGER', 'description': 'Total impressions'},
            'clicks': {'data_type': 'INTEGER', 'description': 'Total clicks'},
            'conversions': {'data_type': 'INTEGER', 'description': 'Attributed conversions'},
        },
        'depends_on': {'nodes': []},
        'raw_sql': '',
        'compiled_sql': '',
    },
    'source.ecommerce.raw_inventory': {
        'name': 'raw_inventory',
        'resource_type': 'source',
        'unique_id': 'source.ecommerce.raw_inventory',
        'description': 'Warehouse inventory levels',
        'relation_name': '"ecommerce"."raw_inventory"',
        'columns': {
            'inventory_id': {'data_type': 'INTEGER', 'description': 'Primary key'},
            'product_id': {'data_type': 'INTEGER', 'description': 'Product FK'},
            'warehouse_id': {'data_type': 'INTEGER', 'description': 'Warehouse FK'},
            'quantity_on_hand': {'data_type': 'INTEGER', 'description': 'Available stock'},
            'quantity_reserved': {'data_type': 'INTEGER', 'description': 'Reserved for orders'},
            'quantity_available': {'data_type': 'INTEGER', 'description': 'Available for sale'},
            'reorder_point': {'data_type': 'INTEGER', 'description': 'Low stock threshold'},
            'last_restocked': {'data_type': 'DATE', 'description': 'Last restock date'},
        },
        'depends_on': {'nodes': []},
        'raw_sql': '',
        'compiled_sql': '',
    },
}
manifest['sources'] = sources

# --- STAGING MODELS ---
staging = {
    'model.ecommerce.stg_orders': {
        'name': 'stg_orders', 'resource_type': 'model',
        'unique_id': 'model.ecommerce.stg_orders',
        'description': 'Staging layer for orders with basic cleaning',
        'relation_name': '"analytics"."stg_orders"',
        'columns': {
            'order_id': {'data_type': 'VARCHAR', 'description': 'Primary key'},
            'customer_id': {'data_type': 'INTEGER', 'description': 'Customer FK'},
            'order_date': {'data_type': 'TIMESTAMP', 'description': 'When order was placed'},
            'order_status': {'data_type': 'VARCHAR', 'description': 'Order status'},
            'net_amount': {'data_type': 'DECIMAL', 'description': 'total_amount minus discount'},
            'shipping_cost': {'data_type': 'DECIMAL', 'description': 'Shipping charge'},
            'payment_method': {'data_type': 'VARCHAR', 'description': 'Payment method'},
        },
        'depends_on': {'nodes': ['source.ecommerce.raw_orders']},
        'raw_sql': 'SELECT order_id, customer_id, order_date, status AS order_status, total_amount - COALESCE(discount_amount, 0) AS net_amount, shipping_cost, payment_method FROM source.ecommerce.raw_orders',
        'compiled_sql': 'SELECT order_id, customer_id, order_date, status AS order_status, total_amount - COALESCE(discount_amount, 0) AS net_amount, shipping_cost, payment_method FROM "ecommerce"."raw_orders"',
    },
    'model.ecommerce.stg_customers': {
        'name': 'stg_customers', 'resource_type': 'model',
        'unique_id': 'model.ecommerce.stg_customers',
        'description': 'Staging layer for customers with name formatting',
        'relation_name': '"analytics"."stg_customers"',
        'columns': {
            'customer_id': {'data_type': 'INTEGER', 'description': 'Primary key'},
            'email': {'data_type': 'VARCHAR', 'description': 'Email (lowercased)'},
            'full_name': {'data_type': 'VARCHAR', 'description': 'first_name + last_name'},
            'phone': {'data_type': 'VARCHAR', 'description': 'Phone number'},
            'country': {'data_type': 'VARCHAR', 'description': 'Country code'},
            'city': {'data_type': 'VARCHAR', 'description': 'City'},
            'customer_segment': {'data_type': 'VARCHAR', 'description': 'Segment'},
            'lifetime_value': {'data_type': 'DECIMAL', 'description': 'LTV'},
            'created_at': {'data_type': 'TIMESTAMP', 'description': 'Account creation'},
        },
        'depends_on': {'nodes': ['source.ecommerce.raw_customers']},
        'raw_sql': "SELECT customer_id, LOWER(email) AS email, first_name || ' ' || last_name AS full_name, phone, country, city, customer_segment, lifetime_value, created_at FROM source.ecommerce.raw_customers",
        'compiled_sql': "SELECT customer_id, LOWER(email) AS email, first_name || ' ' || last_name AS full_name, phone, country, city, customer_segment, lifetime_value, created_at FROM \"ecommerce\".\"raw_customers\"",
    },
    'model.ecommerce.stg_products': {
        'name': 'stg_products', 'resource_type': 'model',
        'unique_id': 'model.ecommerce.stg_products',
        'description': 'Staging layer for products with margin calculation',
        'relation_name': '"analytics"."stg_products"',
        'columns': {
            'product_id': {'data_type': 'INTEGER', 'description': 'Primary key'},
            'sku': {'data_type': 'VARCHAR', 'description': 'SKU'},
            'product_name': {'data_type': 'VARCHAR', 'description': 'Product name'},
            'category': {'data_type': 'VARCHAR', 'description': 'Category'},
            'subcategory': {'data_type': 'VARCHAR', 'description': 'Subcategory'},
            'brand': {'data_type': 'VARCHAR', 'description': 'Brand'},
            'unit_price': {'data_type': 'DECIMAL', 'description': 'List price'},
            'cost': {'data_type': 'DECIMAL', 'description': 'COGS'},
            'margin_pct': {'data_type': 'DECIMAL', 'description': 'Gross margin %'},
            'is_active': {'data_type': 'BOOLEAN', 'description': 'Is active'},
        },
        'depends_on': {'nodes': ['source.ecommerce.raw_products']},
        'raw_sql': 'SELECT product_id, sku, product_name, category, subcategory, brand, unit_price, cost, ROUND((unit_price - cost) / unit_price * 100, 2) AS margin_pct, is_active FROM source.ecommerce.raw_products',
        'compiled_sql': 'SELECT product_id, sku, product_name, category, subcategory, brand, unit_price, cost, ROUND((unit_price - cost) / unit_price * 100, 2) AS margin_pct, is_active FROM "ecommerce"."raw_products"',
    },
    'model.ecommerce.stg_marketing': {
        'name': 'stg_marketing', 'resource_type': 'model',
        'unique_id': 'model.ecommerce.stg_marketing',
        'description': 'Staging layer for marketing campaigns',
        'relation_name': '"analytics"."stg_marketing"',
        'columns': {
            'campaign_id': {'data_type': 'INTEGER', 'description': 'Primary key'},
            'campaign_name': {'data_type': 'VARCHAR', 'description': 'Campaign name'},
            'channel': {'data_type': 'VARCHAR', 'description': 'Marketing channel'},
            'start_date': {'data_type': 'DATE', 'description': 'Campaign start'},
            'end_date': {'data_type': 'DATE', 'description': 'Campaign end'},
            'budget': {'data_type': 'DECIMAL', 'description': 'Budget'},
            'spend': {'data_type': 'DECIMAL', 'description': 'Actual spend'},
            'roas': {'data_type': 'DECIMAL', 'description': 'Return on ad spend'},
            'ctr': {'data_type': 'DECIMAL', 'description': 'Click-through rate'},
        },
        'depends_on': {'nodes': ['source.ecommerce.raw_marketing']},
        'raw_sql': 'SELECT campaign_id, campaign_name, channel, start_date, end_date, budget, spend, CASE WHEN spend > 0 THEN ROUND(conversions * 50 / spend, 2) ELSE 0 END AS roas, CASE WHEN impressions > 0 THEN ROUND(clicks * 100.0 / impressions, 2) ELSE 0 END AS ctr FROM source.ecommerce.raw_marketing',
        'compiled_sql': 'SELECT campaign_id, campaign_name, channel, start_date, end_date, budget, spend, CASE WHEN spend > 0 THEN ROUND(conversions * 50 / spend, 2) ELSE 0 END AS roas, CASE WHEN impressions > 0 THEN ROUND(clicks * 100.0 / impressions, 2) ELSE 0 END AS ctr FROM "ecommerce"."raw_marketing"',
    },
    'model.ecommerce.stg_inventory': {
        'name': 'stg_inventory', 'resource_type': 'model',
        'unique_id': 'model.ecommerce.stg_inventory',
        'description': 'Staging layer for inventory with stock status',
        'relation_name': '"analytics"."stg_inventory"',
        'columns': {
            'inventory_id': {'data_type': 'INTEGER', 'description': 'Primary key'},
            'product_id': {'data_type': 'INTEGER', 'description': 'Product FK'},
            'warehouse_id': {'data_type': 'INTEGER', 'description': 'Warehouse FK'},
            'quantity_on_hand': {'data_type': 'INTEGER', 'description': 'On hand'},
            'quantity_available': {'data_type': 'INTEGER', 'description': 'Available'},
            'reorder_point': {'data_type': 'INTEGER', 'description': 'Reorder threshold'},
            'stock_status': {'data_type': 'VARCHAR', 'description': 'in_stock/low_stock/out_of_stock'},
            'last_restocked': {'data_type': 'DATE', 'description': 'Last restock'},
        },
        'depends_on': {'nodes': ['source.ecommerce.raw_inventory']},
        'raw_sql': "SELECT inventory_id, product_id, warehouse_id, quantity_on_hand, quantity_available, reorder_point, CASE WHEN quantity_available <= 0 THEN 'out_of_stock' WHEN quantity_available <= reorder_point THEN 'low_stock' ELSE 'in_stock' END AS stock_status, last_restocked FROM source.ecommerce.raw_inventory",
        'compiled_sql': "SELECT inventory_id, product_id, warehouse_id, quantity_on_hand, quantity_available, reorder_point, CASE WHEN quantity_available <= 0 THEN 'out_of_stock' WHEN quantity_available <= reorder_point THEN 'low_stock' ELSE 'in_stock' END AS stock_status, last_restocked FROM \"ecommerce\".\"raw_inventory\"",
    },
}
manifest['nodes'].update(staging)

# --- INTERMEDIATE MODELS ---
intermediate = {
    'model.ecommerce.int_order_items': {
        'name': 'int_order_items', 'resource_type': 'model',
        'unique_id': 'model.ecommerce.int_order_items',
        'description': 'Intermediate order items layer',
        'relation_name': '"analytics"."int_order_items"',
        'columns': {
            'order_id': {'data_type': 'VARCHAR', 'description': 'Order FK'},
            'customer_id': {'data_type': 'INTEGER', 'description': 'Customer FK'},
            'order_date': {'data_type': 'TIMESTAMP', 'description': 'Order date'},
            'order_status': {'data_type': 'VARCHAR', 'description': 'Status'},
            'net_amount': {'data_type': 'DECIMAL', 'description': 'Net amount'},
        },
        'depends_on': {'nodes': ['model.ecommerce.stg_orders']},
        'raw_sql': 'SELECT order_id, customer_id, order_date, order_status, net_amount FROM model.ecommerce.stg_orders',
        'compiled_sql': 'SELECT order_id, customer_id, order_date, order_status, net_amount FROM "analytics"."stg_orders"',
    },
    'model.ecommerce.int_order_enrichment': {
        'name': 'int_order_enrichment', 'resource_type': 'model',
        'unique_id': 'model.ecommerce.int_order_enrichment',
        'description': 'Orders enriched with customer info',
        'relation_name': '"analytics"."int_order_enrichment"',
        'columns': {
            'order_id': {'data_type': 'VARCHAR', 'description': 'Order ID'},
            'customer_id': {'data_type': 'INTEGER', 'description': 'Customer ID'},
            'customer_name': {'data_type': 'VARCHAR', 'description': 'Customer full name'},
            'customer_segment': {'data_type': 'VARCHAR', 'description': 'Segment'},
            'country': {'data_type': 'VARCHAR', 'description': 'Country'},
            'order_date': {'data_type': 'TIMESTAMP', 'description': 'Order date'},
            'order_status': {'data_type': 'VARCHAR', 'description': 'Status'},
            'net_amount': {'data_type': 'DECIMAL', 'description': 'Net amount'},
            'payment_method': {'data_type': 'VARCHAR', 'description': 'Payment method'},
            'is_new_customer': {'data_type': 'BOOLEAN', 'description': 'First order flag'},
        },
        'depends_on': {'nodes': ['model.ecommerce.int_order_items', 'model.ecommerce.stg_customers']},
        'raw_sql': 'SELECT o.order_id, o.customer_id, c.full_name AS customer_name, c.customer_segment, c.country, o.order_date, o.order_status, o.net_amount, o.payment_method, CASE WHEN o.order_date = c.created_at THEN TRUE ELSE FALSE END AS is_new_customer FROM model.ecommerce.int_order_items o LEFT JOIN model.ecommerce.stg_customers c ON o.customer_id = c.customer_id',
        'compiled_sql': 'SELECT o.order_id, o.customer_id, c.full_name AS customer_name, c.customer_segment, c.country, o.order_date, o.order_status, o.net_amount, o.payment_method, CASE WHEN o.order_date = c.created_at THEN TRUE ELSE FALSE END AS is_new_customer FROM "analytics"."int_order_items" o LEFT JOIN "analytics"."stg_customers" c ON o.customer_id = c.customer_id',
    },
    'model.ecommerce.int_customer_orders': {
        'name': 'int_customer_orders', 'resource_type': 'model',
        'unique_id': 'model.ecommerce.int_customer_orders',
        'description': 'Aggregated customer order metrics',
        'relation_name': '"analytics"."int_customer_orders"',
        'columns': {
            'customer_id': {'data_type': 'INTEGER', 'description': 'Customer ID'},
            'total_orders': {'data_type': 'INTEGER', 'description': 'Total orders'},
            'total_revenue': {'data_type': 'DECIMAL', 'description': 'Total revenue'},
            'avg_order_value': {'data_type': 'DECIMAL', 'description': 'AOV'},
            'first_order_date': {'data_type': 'TIMESTAMP', 'description': 'First order'},
            'last_order_date': {'data_type': 'TIMESTAMP', 'description': 'Last order'},
        },
        'depends_on': {'nodes': ['model.ecommerce.int_order_enrichment']},
        'raw_sql': 'SELECT customer_id, COUNT(*) AS total_orders, SUM(net_amount) AS total_revenue, AVG(net_amount) AS avg_order_value, MIN(order_date) AS first_order_date, MAX(order_date) AS last_order_date FROM model.ecommerce.int_order_enrichment GROUP BY customer_id',
        'compiled_sql': 'SELECT customer_id, COUNT(*) AS total_orders, SUM(net_amount) AS total_revenue, AVG(net_amount) AS avg_order_value, MIN(order_date) AS first_order_date, MAX(order_date) AS last_order_date FROM "analytics"."int_order_enrichment" GROUP BY customer_id',
    },
    'model.ecommerce.int_product_performance': {
        'name': 'int_product_performance', 'resource_type': 'model',
        'unique_id': 'model.ecommerce.int_product_performance',
        'description': 'Product performance metrics by category',
        'relation_name': '"analytics"."int_product_performance"',
        'columns': {
            'product_id': {'data_type': 'INTEGER', 'description': 'Product ID'},
            'category': {'data_type': 'VARCHAR', 'description': 'Category'},
            'total_units_sold': {'data_type': 'INTEGER', 'description': 'Units sold'},
            'total_revenue': {'data_type': 'DECIMAL', 'description': 'Revenue'},
            'avg_selling_price': {'data_type': 'DECIMAL', 'description': 'ASP'},
        },
        'depends_on': {'nodes': ['model.ecommerce.stg_products']},
        'raw_sql': 'SELECT p.product_id, p.category, 0 AS total_units_sold, 0 AS total_revenue, p.unit_price AS avg_selling_price FROM model.ecommerce.stg_products p',
        'compiled_sql': 'SELECT p.product_id, p.category, 0 AS total_units_sold, 0 AS total_revenue, p.unit_price AS avg_selling_price FROM "analytics"."stg_products" p',
    },
    'model.ecommerce.int_marketing_performance': {
        'name': 'int_marketing_performance', 'resource_type': 'model',
        'unique_id': 'model.ecommerce.int_marketing_performance',
        'description': 'Marketing performance by channel',
        'relation_name': '"analytics"."int_marketing_performance"',
        'columns': {
            'channel': {'data_type': 'VARCHAR', 'description': 'Channel'},
            'total_campaigns': {'data_type': 'INTEGER', 'description': 'Campaigns'},
            'total_budget': {'data_type': 'DECIMAL', 'description': 'Budget'},
            'total_spend': {'data_type': 'DECIMAL', 'description': 'Spend'},
            'total_impressions': {'data_type': 'BIGINT', 'description': 'Impressions'},
            'total_clicks': {'data_type': 'BIGINT', 'description': 'Clicks'},
            'avg_roas': {'data_type': 'DECIMAL', 'description': 'Avg ROAS'},
        },
        'depends_on': {'nodes': ['model.ecommerce.stg_marketing']},
        'raw_sql': 'SELECT channel, COUNT(*) AS total_campaigns, SUM(budget) AS total_budget, SUM(spend) AS total_spend, SUM(impressions) AS total_impressions, SUM(clicks) AS total_clicks, AVG(roas) AS avg_roas FROM model.ecommerce.stg_marketing GROUP BY channel',
        'compiled_sql': 'SELECT channel, COUNT(*) AS total_campaigns, SUM(budget) AS total_budget, SUM(spend) AS total_spend, SUM(impressions) AS total_impressions, SUM(clicks) AS total_clicks, AVG(roas) AS avg_roas FROM "analytics"."stg_marketing" GROUP BY channel',
    },
}
manifest['nodes'].update(intermediate)

# --- MARTS ---
marts = {
    'model.ecommerce.dim_customers': {
        'name': 'dim_customers', 'resource_type': 'model',
        'unique_id': 'model.ecommerce.dim_customers',
        'description': 'Customer dimension table',
        'relation_name': '"analytics"."dim_customers"',
        'columns': {
            'customer_key': {'data_type': 'INTEGER', 'description': 'Surrogate key'},
            'customer_id': {'data_type': 'INTEGER', 'description': 'Natural key'},
            'email': {'data_type': 'VARCHAR', 'description': 'Email'},
            'full_name': {'data_type': 'VARCHAR', 'description': 'Full name'},
            'phone': {'data_type': 'VARCHAR', 'description': 'Phone'},
            'country': {'data_type': 'VARCHAR', 'description': 'Country'},
            'city': {'data_type': 'VARCHAR', 'description': 'City'},
            'customer_segment': {'data_type': 'VARCHAR', 'description': 'Segment'},
            'total_orders': {'data_type': 'INTEGER', 'description': 'Total orders'},
            'total_revenue': {'data_type': 'DECIMAL', 'description': 'Total revenue'},
            'avg_order_value': {'data_type': 'DECIMAL', 'description': 'AOV'},
            'first_order_date': {'data_type': 'TIMESTAMP', 'description': 'First order'},
            'last_order_date': {'data_type': 'TIMESTAMP', 'description': 'Last order'},
            'created_at': {'data_type': 'TIMESTAMP', 'description': 'Account created'},
        },
        'depends_on': {'nodes': ['model.ecommerce.stg_customers', 'model.ecommerce.int_customer_orders']},
        'raw_sql': 'SELECT c.customer_id AS customer_key, c.customer_id, c.email, c.full_name, c.phone, c.country, c.city, c.customer_segment, COALESCE(co.total_orders, 0) AS total_orders, COALESCE(co.total_revenue, 0) AS total_revenue, COALESCE(co.avg_order_value, 0) AS avg_order_value, co.first_order_date, co.last_order_date, c.created_at FROM model.ecommerce.stg_customers c LEFT JOIN model.ecommerce.int_customer_orders co ON c.customer_id = co.customer_id',
        'compiled_sql': 'SELECT c.customer_id AS customer_key, c.customer_id, c.email, c.full_name, c.phone, c.country, c.city, c.customer_segment, COALESCE(co.total_orders, 0) AS total_orders, COALESCE(co.total_revenue, 0) AS total_revenue, COALESCE(co.avg_order_value, 0) AS avg_order_value, co.first_order_date, co.last_order_date, c.created_at FROM "analytics"."stg_customers" c LEFT JOIN "analytics"."int_customer_orders" co ON c.customer_id = co.customer_id',
    },
    'model.ecommerce.dim_products': {
        'name': 'dim_products', 'resource_type': 'model',
        'unique_id': 'model.ecommerce.dim_products',
        'description': 'Product dimension table',
        'relation_name': '"analytics"."dim_products"',
        'columns': {
            'product_key': {'data_type': 'INTEGER', 'description': 'Surrogate key'},
            'product_id': {'data_type': 'INTEGER', 'description': 'Natural key'},
            'sku': {'data_type': 'VARCHAR', 'description': 'SKU'},
            'product_name': {'data_type': 'VARCHAR', 'description': 'Product name'},
            'category': {'data_type': 'VARCHAR', 'description': 'Category'},
            'subcategory': {'data_type': 'VARCHAR', 'description': 'Subcategory'},
            'brand': {'data_type': 'VARCHAR', 'description': 'Brand'},
            'unit_price': {'data_type': 'DECIMAL', 'description': 'List price'},
            'cost': {'data_type': 'DECIMAL', 'description': 'COGS'},
            'margin_pct': {'data_type': 'DECIMAL', 'description': 'Margin %'},
            'is_active': {'data_type': 'BOOLEAN', 'description': 'Is active'},
        },
        'depends_on': {'nodes': ['model.ecommerce.stg_products']},
        'raw_sql': 'SELECT p.product_id AS product_key, p.product_id, p.sku, p.product_name, p.category, p.subcategory, p.brand, p.unit_price, p.cost, p.margin_pct, p.is_active FROM model.ecommerce.stg_products p',
        'compiled_sql': 'SELECT p.product_id AS product_key, p.product_id, p.sku, p.product_name, p.category, p.subcategory, p.brand, p.unit_price, p.cost, p.margin_pct, p.is_active FROM "analytics"."stg_products" p',
    },
    'model.ecommerce.fct_orders': {
        'name': 'fct_orders', 'resource_type': 'model',
        'unique_id': 'model.ecommerce.fct_orders',
        'description': 'Order fact table — central fact for order analytics',
        'relation_name': '"analytics"."fct_orders"',
        'columns': {
            'order_key': {'data_type': 'VARCHAR', 'description': 'Surrogate key'},
            'order_id': {'data_type': 'VARCHAR', 'description': 'Natural key'},
            'customer_key': {'data_type': 'INTEGER', 'description': 'Customer FK'},
            'order_date': {'data_type': 'TIMESTAMP', 'description': 'Order date'},
            'order_hour': {'data_type': 'INTEGER', 'description': 'Hour of day'},
            'order_day_of_week': {'data_type': 'INTEGER', 'description': 'Day of week'},
            'order_month': {'data_type': 'INTEGER', 'description': 'Month'},
            'order_year': {'data_type': 'INTEGER', 'description': 'Year'},
            'order_status': {'data_type': 'VARCHAR', 'description': 'Status'},
            'net_amount': {'data_type': 'DECIMAL', 'description': 'Net amount'},
            'payment_method': {'data_type': 'VARCHAR', 'description': 'Payment'},
            'country': {'data_type': 'VARCHAR', 'description': 'Country'},
            'customer_segment': {'data_type': 'VARCHAR', 'description': 'Segment'},
            'is_new_customer': {'data_type': 'BOOLEAN', 'description': 'New customer flag'},
        },
        'depends_on': {'nodes': ['model.ecommerce.int_order_enrichment']},
        'raw_sql': 'SELECT o.order_id AS order_key, o.order_id, o.customer_id AS customer_key, o.order_date, HOUR(o.order_date) AS order_hour, DAYOFWEEK(o.order_date) AS order_day_of_week, MONTH(o.order_date) AS order_month, YEAR(o.order_date) AS order_year, o.order_status, o.net_amount, o.payment_method, o.country, o.customer_segment, o.is_new_customer FROM model.ecommerce.int_order_enrichment o',
        'compiled_sql': 'SELECT o.order_id AS order_key, o.order_id, o.customer_id AS customer_key, o.order_date, HOUR(o.order_date) AS order_hour, DAYOFWEEK(o.order_date) AS order_day_of_week, MONTH(o.order_date) AS order_month, YEAR(o.order_date) AS order_year, o.order_status, o.net_amount, o.payment_method, o.country, o.customer_segment, o.is_new_customer FROM "analytics"."int_order_enrichment" o',
    },
    'model.ecommerce.fct_revenue': {
        'name': 'fct_revenue', 'resource_type': 'model',
        'unique_id': 'model.ecommerce.fct_revenue',
        'description': 'Revenue fact table with daily and segment aggregations',
        'relation_name': '"analytics"."fct_revenue"',
        'columns': {
            'date_day': {'data_type': 'DATE', 'description': 'Calendar date'},
            'customer_segment': {'data_type': 'VARCHAR', 'description': 'Segment'},
            'country': {'data_type': 'VARCHAR', 'description': 'Country'},
            'total_orders': {'data_type': 'INTEGER', 'description': 'Orders'},
            'total_revenue': {'data_type': 'DECIMAL', 'description': 'Revenue'},
            'avg_order_value': {'data_type': 'DECIMAL', 'description': 'AOV'},
            'new_customers': {'data_type': 'INTEGER', 'description': 'New customers'},
        },
        'depends_on': {'nodes': ['model.ecommerce.fct_orders']},
        'raw_sql': 'SELECT CAST(o.order_date AS DATE) AS date_day, o.customer_segment, o.country, COUNT(*) AS total_orders, SUM(o.net_amount) AS total_revenue, AVG(o.net_amount) AS avg_order_value, COUNTIF(o.is_new_customer = TRUE) AS new_customers FROM model.ecommerce.fct_orders o GROUP BY CAST(o.order_date AS DATE), o.customer_segment, o.country',
        'compiled_sql': 'SELECT CAST(o.order_date AS DATE) AS date_day, o.customer_segment, o.country, COUNT(*) AS total_orders, SUM(o.net_amount) AS total_revenue, AVG(o.net_amount) AS avg_order_value, COUNTIF(o.is_new_customer = TRUE) AS new_customers FROM "analytics"."fct_orders" o GROUP BY CAST(o.order_date AS DATE), o.customer_segment, o.country',
    },
    'model.ecommerce.fct_marketing': {
        'name': 'fct_marketing', 'resource_type': 'model',
        'unique_id': 'model.ecommerce.fct_marketing',
        'description': 'Marketing fact table aggregated by campaign',
        'relation_name': '"analytics"."fct_marketing"',
        'columns': {
            'campaign_key': {'data_type': 'INTEGER', 'description': 'Surrogate key'},
            'campaign_id': {'data_type': 'INTEGER', 'description': 'Campaign ID'},
            'campaign_name': {'data_type': 'VARCHAR', 'description': 'Campaign name'},
            'channel': {'data_type': 'VARCHAR', 'description': 'Channel'},
            'start_date': {'data_type': 'DATE', 'description': 'Start'},
            'end_date': {'data_type': 'DATE', 'description': 'End'},
            'budget': {'data_type': 'DECIMAL', 'description': 'Budget'},
            'spend': {'data_type': 'DECIMAL', 'description': 'Spend'},
            'roas': {'data_type': 'DECIMAL', 'description': 'ROAS'},
            'ctr': {'data_type': 'DECIMAL', 'description': 'CTR'},
        },
        'depends_on': {'nodes': ['model.ecommerce.stg_marketing']},
        'raw_sql': 'SELECT m.campaign_id AS campaign_key, m.campaign_id, m.campaign_name, m.channel, m.start_date, m.end_date, m.budget, m.spend, m.roas, m.ctr FROM model.ecommerce.stg_marketing m',
        'compiled_sql': 'SELECT m.campaign_id AS campaign_key, m.campaign_id, m.campaign_name, m.channel, m.start_date, m.end_date, m.budget, m.spend, m.roas, m.ctr FROM "analytics"."stg_marketing" m',
    },
}
manifest['nodes'].update(marts)

# --- Build parent_map and child_map ---
all_nodes = {**manifest['nodes'], **manifest['sources']}
for uid, node in all_nodes.items():
    manifest['parent_map'][uid] = node.get('depends_on', {}).get('nodes', [])
    children = [n for n, nd in all_nodes.items() if uid in nd.get('depends_on', {}).get('nodes', [])]
    manifest['child_map'][uid] = children

with open(r'C:\Users\mrham\cascade-data\cascade-rebuild\demo\manifest.json', 'w', encoding='utf-8') as f:
    json.dump(manifest, f, indent=2, ensure_ascii=False)

print('manifest.json written successfully')
print(f'Total nodes: {len(manifest["nodes"])}')
print(f'Total sources: {len(manifest["sources"])}')
print(f'Total: {len(manifest["nodes"]) + len(manifest["sources"])}')
