"""
Upload zone component — drag-and-drop manifest.json uploader.
"""

import json
from pathlib import Path

import streamlit as st


def render_upload_zone() -> tuple[dict | None, dict | None]:
    """
    Render the upload zone and return (manifest_data, catalog_data).
    Returns (None, None) if no file was uploaded.
    """
    # Single full-width dropzone for the manifest.
    uploaded_file = st.file_uploader(
        "Drop manifest.json here or click to browse",
        type=["json"],
        help="Upload the manifest.json file generated by `dbt compile` or `dbt build`",
        label_visibility="collapsed",
        key="manifest_uploader",
    )

    # Optional catalog as a smaller secondary dropzone below.
    catalog_file = st.file_uploader(
        "Optional: catalog.json (for column descriptions)",
        type=["json"],
        help="Upload catalog.json for enriched column descriptions",
        label_visibility="collapsed",
        key="catalog_uploader",
    )

    manifest_data = None
    catalog_data = None

    if uploaded_file is not None:
        try:
            manifest_data = json.load(uploaded_file)

            # Validate manifest structure
            if "nodes" not in manifest_data and "sources" not in manifest_data:
                st.error("Invalid manifest.json: missing 'nodes' or 'sources' key.")
                return None, None

            # Count resources
            node_count = len(manifest_data.get("nodes", {}))
            source_count = len(manifest_data.get("sources", {}))
            total = node_count + source_count

            st.success(f"Loaded {total:,} resources ({node_count:,} nodes, {source_count:,} sources)")

        except json.JSONDecodeError as e:
            st.error(f"Invalid JSON: {e}")
            return None, None
        except Exception as e:
            st.error(f"Error reading manifest: {e}")
            return None, None

    if catalog_file is not None:
        try:
            catalog_data = json.load(catalog_file)
            st.success("Catalog loaded for enriched column metadata")
        except json.JSONDecodeError as e:
            st.warning(f"Catalog JSON parse error: {e} — ignoring catalog")
            catalog_data = None
        except Exception as e:
            st.warning(f"Could not load catalog: {e}")
            catalog_data = None

    return manifest_data, catalog_data


def render_try_demo_button() -> bool:
    """
    Render a 'Try Demo' button in the sidebar.
    Returns True if the demo button was clicked.
    """
    return st.button(
        "🎲 Try Demo",
        help="Load a sample e-commerce dbt project to explore the dashboard",
        use_container_width=True,
        key="try_demo_btn",
    )


def load_demo_manifest() -> tuple[dict, dict | None]:
    """
    Load the built-in demo manifest.json.
    Returns (manifest_dict, None).
    """
    demo_path = Path(__file__).parent.parent / "demo" / "manifest.json"

    if demo_path.exists():
        with open(demo_path, encoding="utf-8") as f:
            manifest = json.load(f)
        return manifest, None
    else:
        # Generate a minimal demo manifest
        return _generate_minimal_demo(), None


def _generate_minimal_demo() -> dict:
    """Generate a minimal demo manifest with 3 source + 4 model nodes."""
    return {
        "metadata": {
            "dbt_version": "1.8.0",
            "adapter_type": "snowflake",
            "project_name": "demo_ecommerce",
            "generated_at": "2026-06-08T12:00:00Z",
        },
        "nodes": {
            "model.demo_ecommerce.stg_orders": {
                "unique_id": "model.demo_ecommerce.stg_orders",
                "name": "stg_orders",
                "resource_type": "model",
                "schema": "analytics",
                "database": "demo_db",
                "description": "Staged order data with customer info",
                "compiled_code": "SELECT order_id, customer_id, order_date, total FROM raw_orders",
                "raw_code": "SELECT order_id, customer_id, order_date, total FROM {{ source('raw', 'orders') }}",
                "columns": {
                    "order_id": {"name": "order_id", "data_type": "VARCHAR", "description": "Primary key"},
                    "customer_id": {"name": "customer_id", "data_type": "VARCHAR", "description": "Customer FK"},
                    "order_date": {"name": "order_date", "data_type": "DATE", "description": "Order date"},
                    "total": {"name": "total", "data_type": "DECIMAL", "description": "Order total"},
                },
                "depends_on": {"nodes": ["source.demo_ecommerce.raw_orders"]},
                "relation_name": "demo_db.analytics.stg_orders",
            },
            "model.demo_ecommerce.stg_customers": {
                "unique_id": "model.demo_ecommerce.stg_customers",
                "name": "stg_customers",
                "resource_type": "model",
                "schema": "analytics",
                "database": "demo_db",
                "description": "Staged customer data",
                "compiled_code": "SELECT customer_id, name, email, created_at FROM raw_customers",
                "raw_code": "SELECT customer_id, name, email, created_at FROM {{ source('raw', 'customers') }}",
                "columns": {
                    "customer_id": {"name": "customer_id", "data_type": "VARCHAR", "description": "PK"},
                    "name": {"name": "name", "data_type": "VARCHAR", "description": "Full name"},
                    "email": {"name": "email", "data_type": "VARCHAR", "description": "Email address"},
                    "created_at": {"name": "created_at", "data_type": "TIMESTAMP", "description": "Created at"},
                },
                "depends_on": {"nodes": ["source.demo_ecommerce.raw_customers"]},
                "relation_name": "demo_db.analytics.stg_customers",
            },
            "model.demo_ecommerce.fct_orders": {
                "unique_id": "model.demo_ecommerce.fct_orders",
                "name": "fct_orders",
                "resource_type": "model",
                "schema": "analytics",
                "database": "demo_db",
                "description": "Fact orders — enriched with customer data",
                "compiled_code": "SELECT o.order_id, o.customer_id, c.name AS customer_name, o.order_date, o.total FROM stg_orders o JOIN stg_customers c ON o.customer_id = c.customer_id",
                "raw_code": "SELECT o.order_id, o.customer_id, c.name AS customer_name, o.order_date, o.total FROM {{ ref('stg_orders') }} o JOIN {{ ref('stg_customers') }} c ON o.customer_id = c.customer_id",
                "columns": {
                    "order_id": {"name": "order_id", "data_type": "VARCHAR", "description": "PK"},
                    "customer_id": {"name": "customer_id", "data_type": "VARCHAR", "description": "FK"},
                    "customer_name": {"name": "customer_name", "data_type": "VARCHAR", "description": "Denormalized from customers"},
                    "order_date": {"name": "order_date", "data_type": "DATE", "description": "Date"},
                    "total": {"name": "total", "data_type": "DECIMAL", "description": "Amount"},
                },
                "depends_on": {"nodes": ["model.demo_ecommerce.stg_orders", "model.demo_ecommerce.stg_customers"]},
                "relation_name": "demo_db.analytics.fct_orders",
            },
            "model.demo_ecommerce.dim_customers": {
                "unique_id": "model.demo_ecommerce.dim_customers",
                "name": "dim_customers",
                "resource_type": "model",
                "schema": "analytics",
                "database": "demo_db",
                "description": "Customer dimension table",
                "compiled_code": "SELECT customer_id, name, email, created_at FROM stg_customers",
                "raw_code": "SELECT customer_id, name, email, created_at FROM {{ ref('stg_customers') }}",
                "columns": {
                    "customer_id": {"name": "customer_id", "data_type": "VARCHAR", "description": "PK"},
                    "name": {"name": "name", "data_type": "VARCHAR", "description": "Full name"},
                    "email": {"name": "email", "data_type": "VARCHAR", "description": "Email"},
                    "created_at": {"name": "created_at", "data_type": "TIMESTAMP", "description": "Created"},
                },
                "depends_on": {"nodes": ["model.demo_ecommerce.stg_customers"]},
                "relation_name": "demo_db.analytics.dim_customers",
            },
        },
        "sources": {
            "source.demo_ecommerce.raw_orders": {
                "unique_id": "source.demo_ecommerce.raw_orders",
                "name": "raw_orders",
                "resource_type": "source",
                "schema": "raw",
                "database": "demo_db",
                "description": "Raw orders from the OLTP system",
                "columns": {
                    "order_id": {"name": "order_id", "data_type": "VARCHAR", "description": "PK"},
                    "customer_id": {"name": "customer_id", "data_type": "VARCHAR", "description": "FK"},
                    "order_date": {"name": "order_date", "data_type": "DATE", "description": "Date"},
                    "total": {"name": "total", "data_type": "DECIMAL", "description": "Amount"},
                },
                "relation_name": "demo_db.raw.raw_orders",
            },
            "source.demo_ecommerce.raw_customers": {
                "unique_id": "source.demo_ecommerce.raw_customers",
                "name": "raw_customers",
                "resource_type": "source",
                "schema": "raw",
                "database": "demo_db",
                "description": "Raw customers from the OLTP system",
                "columns": {
                    "customer_id": {"name": "customer_id", "data_type": "VARCHAR", "description": "PK"},
                    "name": {"name": "name", "data_type": "VARCHAR", "description": "Full name"},
                    "email": {"name": "email", "data_type": "VARCHAR", "description": "Email"},
                    "created_at": {"name": "created_at", "data_type": "TIMESTAMP", "description": "Created"},
                },
                "relation_name": "demo_db.raw.raw_customers",
            },
        },
    }
